spring:
    datasource:
        url: jdbc:h2:mem:test;MODE=MySQL
        driver-class-name: org.h2.Driver
        username: sa
        password:
        schema: classpath:schema/*.sql
        data: classpath:data/*.sql
j2cache:
    config-location: /j2cache.properties
    redisClient: lettuce